
server:
  port: 8070

spring:
  datasource:
    url: jdbc:mysql://192.168.83.142:3306/silentiger-mall-nacos?charset=UTF-8&locale=en_US.UTF-8&timezone=UTC-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver


knife4j:
  enable: true
  openapi:
    title: 统一认证中心
    description: "用户登录、权限等认证中心"
    email: yuyunhu225@gmail.com
    concat: silentiger@yyh
    url: \
    version: v1.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
    group:
      test1:
        group-name: default
        api-rule: package
        api-rule-resources:
          - org.example.controller