
server:
  port: 9999


spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        # 采用自定义路由 ID
        - id: mall-cloud-demo
          #lb 表示从 nacos 中按照名称获取微服务,并遵循负载均衡策略，user-service 对应微服务应用名
          uri: lb://mall-cloud-demo
          # 断言，路径匹配
          predicates:
            - Path=/mall-cloud-demo/**
          filters:
            - StripPrefix=1       # 使用过滤器 
          #   - RewritePath=/mall-demo(?<segment>/?.*), /$\{segment}
        - id: mall-admin
          uri: lb://mall-admin
          predicates:
            - Path=/mall-admin/**
          filters:
            - StripPrefix=1       # 使用过滤器 
        - id: mall-auth
          uri: lb://mall-auth
          predicates:
            - Path=/mall-auth/**
          filters:
            - StripPrefix=1       # 使用过滤器 
        - id: mall-portal
          uri: lb://mall-portal
          predicates:
            - Path=/mall-portal/**
          filters:
            - StripPrefix=1       # 使用过滤器 
        - id: mall-search
          uri: lb://mall-search
          predicates:
            - Path=/mall-search/**
          filters:
            - StripPrefix=1       # 使用过滤器 

# 关于filters的各种过滤器说明：
# - StripPrefix=1: 以http://localhost:9999/mall-demo/demo/time为例
  # 若无StripPrefix，网关转发到微服务的请求不会过滤掉前缀mall-demo
  # 若有StripPrefix，网关转发到微服务的请求w'w'w会过滤掉前缀mall-demo，=1代表过滤掉一个前缀
knife4j:
  gateway:
    # ① 第一个配置，开启gateway聚合组件
    enabled: true
    # ② 第二行配置，设置聚合模式采用discover服务发现的模式
    strategy: discover
    discover:
      # ③ 第三行配置，开启discover模式
      enabled: true
      # ④ 第四行配置，聚合子服务全部为Swagger2规范的文档
      version: swagger2